### ISSUE TITLE
New mtproto proxy source

### ISSUE THREAD

**Issue by subsys-R9boq8** [NekoX-Dev/ProxyListBot#1]
- Type: Telegram Channel
- Address: https://t.me/chinagrassroot
- Proxy type: mtproto proxy
- Subscriber number: 2,868, safe for use and blend in.
- Messages require further processing: Yes, contains other links and contents.
- Proxy Link Format: https://t.me/proxy?xxx and tg://proxy?xxx

**Comment by nekohasekai** [comment]
thanks
